# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dani3l's Tech Couch
author: Daniel Wagner
email: daniel@wagners.name
description: >- # this means to ignore newlines until "baseurl:"
  Daniel's blog on technology, coding and other nerd stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.wagners.name" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: daniel_wagn3r
github_username:  kwaxi
google_analytics: GTM-KQZCCL

social:
  name: Daniel Wagner
  links:
    - https://www.facebook.com/daniel.wagn3r
    - https://twitter.com/daniel_wagn3r
    - https://www.instagram.com/daniel.wagn3r/
    - https://github.com/kwaxi/
    - https://plus.google.com/+DanielWagner79
    - https://www.linkedin.com/in/danielwagn3r
    - https://www.xing.com/profile/Daniel_Wagner314
    - https://keybase.io/danielwagner

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-seo-tag  
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
